copyright: Copyright &copy; 2023 huxuan
extra:
  social:
    - icon: fontawesome/brands/github
      link: http://github.com/serious-scaffold/serious-scaffold-python
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/serious-scaffold/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mkdocs-click
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
nav:
  - index.md
  - Reference:
      - cli.md
      - settings.md
plugins:
  - git-revision-date-localized
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          paths: [src]
          options:
            heading_level: 3
            show_root_full_path: false
            separate_signature: true
  - search
repo_url: http://github.com/serious-scaffold/serious-scaffold-python
site_name: Serious Scaffold Python
site_description: A development-focused Python project template with various integrations, configurations and modules.
theme:
  custom_dir: docs/templates
  favicon: assets/logo.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    edit: material/pencil
    repo: fontawesome/brands/github
    view: material/eye
  logo: assets/logo.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: light blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
watch:
  - README.md
  - src
