name: Renovate
jobs:
  renovate:
    container:
      env:
        LOG_LEVEL: debug
        RENOVATE_BRANCH_PREFIX: renovate-github/
        RENOVATE_ENABLED_MANAGERS: '["pep621", "github-actions"]'
        RENOVATE_GIT_AUTHOR: Renovate GitHub Bot <github@renovatebot.com>
        RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
        RENOVATE_PLATFORM: github
        RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
        RENOVATE_REPOSITORY_CACHE: enabled
        RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
      image: ghcr.io/renovatebot/renovate:37.202.2@sha256:6b5508487d42dcd36f95ff1139958f3b755bc8ff77b805b86eb1c59db943ef2f
      options: '--user root'
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - id: generate-token
        name: Generate a token
        if: vars.BOT_APP_ID
        uses: actions/create-github-app-token@e8e39f73bb84fdf315a015fa3104f314c0a258b4 # v1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN || steps.generate-token.outputs.token }}
        run: |
          if [ -z "$RENOVATE_TOKEN" ]; then
            echo "RENOVATE_TOKEN is not properly configured, skipping ..."
          else
            renovate $RENOVATE_EXTRA_FLAG
          fi
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * 0,6'
  workflow_dispatch: null
